# -*- coding: utf-8 -*-
"""Supervised Learning: Regression  Models and Performance Metrics |  Solution

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjiAAuQ9YbQy-LhhcI7Qg4kp72eGxcJK

# **Assignment: Supervised Learning – Regression Models and Performance Metrics**

---

## **Question 1: What is Simple Linear Regression (SLR)? Explain its purpose.**

### **Answer:**

**Simple Linear Regression (SLR)** is a statistical technique used to model the relationship between **one independent variable (X)** and **one dependent variable (Y)** by fitting a straight line.

### **Purpose:**

* To understand the relationship between variables
* To predict the value of Y based on X
* To identify trends and patterns

### **Example:**

* Predicting house price based on area
* Predicting marks based on study hours

---

## **Question 2: Key Assumptions of Simple Linear Regression**

### **Answer:**

1. **Linearity**

   * Relationship between X and Y must be linear

2. **Independence**

   * Observations must be independent

3. **Homoscedasticity**

   * Constant variance of errors

4. **Normality of Errors**

   * Residuals should be normally distributed

5. **No Multicollinearity**

   * (Mostly for multiple regression) independent variables should not be highly correlated

---

## **Question 3: Mathematical Equation of SLR**

### **Answer:**

[
Y = \beta_0 + \beta_1 X + \epsilon
]

### **Explanation of Terms:**

* **Y** → Dependent variable (output)
* **X** → Independent variable (input)
* **β₀ (Intercept)** → Value of Y when X = 0
* **β₁ (Slope)** → Change in Y per unit change in X
* **ε (Error term)** → Difference between actual and predicted values

---

## **Question 4: Real-World Example**

### **Answer:**

**Example: Salary Prediction**

* Independent Variable (X): Years of experience
* Dependent Variable (Y): Salary

### **Explanation:**

* As experience increases, salary tends to increase
* SLR helps predict expected salary for a given experience

---

## **Question 5: Method of Least Squares**

### **Answer:**

The **method of least squares** is used to find the best-fitting regression line by minimizing the **sum of squared errors** between actual and predicted values.

### **Formula:**

[
\text{Minimize } \sum (Y_i - \hat{Y_i})^2
]

### **Explanation:**

* Calculates the line where total error is smallest
* Ensures best approximation of data points

---

## **Question 6: Logistic Regression vs Linear Regression**

### **Answer:**

### **Logistic Regression**

* Used for **classification problems**
* Output is probability (0 to 1)
* Uses **Sigmoid function**

### **Linear Regression**

* Used for **continuous prediction**
* Output is a real number
* Uses straight line equation

---

### **Key Differences:**

| Feature  | Linear Regression | Logistic Regression |
| -------- | ----------------- | ------------------- |
| Output   | Continuous        | Categorical         |
| Function | Linear            | Sigmoid             |
| Use Case | Prediction        | Classification      |

---

## **Question 7: Three Evaluation Metrics for Regression**

### **Answer:**

### **1. Mean Absolute Error (MAE)**

* Average of absolute differences
  [
  MAE = \frac{1}{n} \sum |Y - \hat{Y}|
  ]

---

### **2. Mean Squared Error (MSE)**

* Average of squared differences
  [
  MSE = \frac{1}{n} \sum (Y - \hat{Y})^2
  ]

---

### **3. Root Mean Squared Error (RMSE)**

* Square root of MSE
  [
  RMSE = \sqrt{MSE}
  ]

---

## **Question 8: Purpose of R-Squared**

### **Answer:**

**R-squared (R²)** measures how well the regression model explains the variability of the dependent variable.

### **Range:**

* 0 → No explanation
* 1 → Perfect explanation

### **Interpretation:**

* Higher R² → Better model fit
* Example: R² = 0.85 means 85% variance explained

---

## **Question 9: Python Code for Simple Linear Regression**

### **Answer:**

```python
import numpy as np
from sklearn.linear_model import LinearRegression

# Sample data
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
Y = np.array([2, 4, 5, 4, 5])

# Model
model = LinearRegression()
model.fit(X, Y)

# Output
print("Slope:", model.coef_[0])
print("Intercept:", model.intercept_)
```

### **Output (Example):**

```
Slope: 0.8
Intercept: 1.6
```

---

## **Question 10: Interpretation of Coefficients**

### **Answer:**

### **Intercept (β₀):**

* Value of Y when X = 0
* Starting point of regression line

### **Slope (β₁):**

* Represents change in Y for one unit increase in X

---

### **Example:**

If equation is:
[
Y = 2 + 3X
]

* Intercept = 2 → Base value
* Slope = 3 → Y increases by 3 for each unit increase in X
"""

